import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "./globals.css";
import Providers from "@/lib/provider";
import Navbar from "@/components/partials/Navbar";
import Footer from "@/components/partials/Footer";

const open_sans = Open_Sans({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800"],
});

export const metadata: Metadata = {
  title: "Tech Store",
  description: "Generated by Hakan Karaahmetoglu and Lutfullah Celenk",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`flex flex-col bg-secondary-400  min-h-screen dark:bg-primary-300 ${open_sans.className}`}
      >
        <Navbar />
        <Providers>{children}</Providers>
        <Footer />
      </body>
    </html>
  );
}
